import { describe, expect, it } from "vitest";
import { createApp, routeMounts } from "../app.js";
import { autoGeneratedRouteKeys, BESPOKE_ROUTE_KEYS } from "./authMatrix.data.js";
import { PUBLIC_ROUTES } from "./publicRoutes.js";
import { buildRouteInventory, type DiscoveredRoute } from "./routeInventory.js";

function routeKey(route: DiscoveredRoute): string {
  return `${route.method} ${route.path}`;
}

const app = createApp();
const inventory = buildRouteInventory(app, routeMounts);

describe("route-guard inventory", () => {
  it("discovered a plausible number of routes (sanity check on the walker itself)", () => {
    // If this drops to a handful, the walker is broken, not the app — the
    // real app.ts wires up dozens of routes across 15+ modules.
    expect(inventory.length).toBeGreaterThan(50);
  });

  it("every public-allowlisted route actually exists in the app", () => {
    const discoveredKeys = new Set(inventory.map(routeKey));
    const missing = [...PUBLIC_ROUTES].filter((key) => !discoveredKeys.has(key));
    expect(missing).toEqual([]);
  });

  it("every non-public route has an auth-matrix row (auto-generated or bespoke)", () => {
    const matrixKeys = new Set([...autoGeneratedRouteKeys(inventory), ...BESPOKE_ROUTE_KEYS]);
    const uncovered = inventory
      .map(routeKey)
      .filter((key) => !PUBLIC_ROUTES.has(key) && !matrixKeys.has(key));
    expect(
      uncovered,
      `These routes have a guard but no auth-matrix coverage. Add them to authMatrix.data.ts ` +
        `(buildAutoRows picks up pure requireRole routes automatically; anything mixed with ` +
        `requireScope needs a bespoke row and an entry in BESPOKE_ROUTE_KEYS).`,
    ).toEqual([]);
  });

  describe.each(inventory.map((route) => ({ route, key: routeKey(route) })))(
    "$key",
    ({ route, key }) => {
      it("is either on the public allowlist or carries an explicit role/scope guard", () => {
        if (PUBLIC_ROUTES.has(key)) {
          return;
        }

        const hasAuth = route.guardTypes.has("auth");
        const hasRoleOrScope = route.guardTypes.has("role") || route.guardTypes.has("scope");

        expect(
          hasAuth && hasRoleOrScope,
          `${key} must have requireAuth AND (requireRole or requireScope), or be added to ` +
            `PUBLIC_ROUTES with a reason. Found guard types: [${[...route.guardTypes].join(", ") || "none"}]`,
        ).toBe(true);
      });
    },
  );
});
