/// The 114 surahs of the Qur'an — number, transliterated name, common English
/// meaning, and ayah count. Standard, unchanging reference data.
export interface SurahSeedRow {
  number: number;
  name: string;
  englishName: string;
  totalAyahs: number;
}

export const SURAHS: SurahSeedRow[] = [
  { number: 1, name: "Al-Fatihah", englishName: "The Opening", totalAyahs: 7 },
  { number: 2, name: "Al-Baqarah", englishName: "The Cow", totalAyahs: 286 },
  { number: 3, name: "Aal-E-Imran", englishName: "The Family of Imran", totalAyahs: 200 },
  { number: 4, name: "An-Nisa", englishName: "The Women", totalAyahs: 176 },
  { number: 5, name: "Al-Ma'idah", englishName: "The Table Spread", totalAyahs: 120 },
  { number: 6, name: "Al-An'am", englishName: "The Cattle", totalAyahs: 165 },
  { number: 7, name: "Al-A'raf", englishName: "The Heights", totalAyahs: 206 },
  { number: 8, name: "Al-Anfal", englishName: "The Spoils of War", totalAyahs: 75 },
  { number: 9, name: "At-Tawbah", englishName: "The Repentance", totalAyahs: 129 },
  { number: 10, name: "Yunus", englishName: "Jonah", totalAyahs: 109 },
  { number: 11, name: "Hud", englishName: "Hud", totalAyahs: 123 },
  { number: 12, name: "Yusuf", englishName: "Joseph", totalAyahs: 111 },
  { number: 13, name: "Ar-Ra'd", englishName: "The Thunder", totalAyahs: 43 },
  { number: 14, name: "Ibrahim", englishName: "Abraham", totalAyahs: 52 },
  { number: 15, name: "Al-Hijr", englishName: "The Rocky Tract", totalAyahs: 99 },
  { number: 16, name: "An-Nahl", englishName: "The Bee", totalAyahs: 128 },
  { number: 17, name: "Al-Isra", englishName: "The Night Journey", totalAyahs: 111 },
  { number: 18, name: "Al-Kahf", englishName: "The Cave", totalAyahs: 110 },
  { number: 19, name: "Maryam", englishName: "Mary", totalAyahs: 98 },
  { number: 20, name: "Ta-Ha", englishName: "Ta-Ha", totalAyahs: 135 },
  { number: 21, name: "Al-Anbiya", englishName: "The Prophets", totalAyahs: 112 },
  { number: 22, name: "Al-Hajj", englishName: "The Pilgrimage", totalAyahs: 78 },
  { number: 23, name: "Al-Mu'minun", englishName: "The Believers", totalAyahs: 118 },
  { number: 24, name: "An-Nur", englishName: "The Light", totalAyahs: 64 },
  { number: 25, name: "Al-Furqan", englishName: "The Criterion", totalAyahs: 77 },
  { number: 26, name: "Ash-Shu'ara", englishName: "The Poets", totalAyahs: 227 },
  { number: 27, name: "An-Naml", englishName: "The Ant", totalAyahs: 93 },
  { number: 28, name: "Al-Qasas", englishName: "The Stories", totalAyahs: 88 },
  { number: 29, name: "Al-Ankabut", englishName: "The Spider", totalAyahs: 69 },
  { number: 30, name: "Ar-Rum", englishName: "The Romans", totalAyahs: 60 },
  { number: 31, name: "Luqman", englishName: "Luqman", totalAyahs: 34 },
  { number: 32, name: "As-Sajdah", englishName: "The Prostration", totalAyahs: 30 },
  { number: 33, name: "Al-Ahzab", englishName: "The Combined Forces", totalAyahs: 73 },
  { number: 34, name: "Saba", englishName: "Sheba", totalAyahs: 54 },
  { number: 35, name: "Fatir", englishName: "Originator", totalAyahs: 45 },
  { number: 36, name: "Ya-Sin", englishName: "Ya-Sin", totalAyahs: 83 },
  { number: 37, name: "As-Saffat", englishName: "Those Who Set The Ranks", totalAyahs: 182 },
  { number: 38, name: "Sad", englishName: "Sad", totalAyahs: 88 },
  { number: 39, name: "Az-Zumar", englishName: "The Troops", totalAyahs: 75 },
  { number: 40, name: "Ghafir", englishName: "The Forgiver", totalAyahs: 85 },
  { number: 41, name: "Fussilat", englishName: "Explained In Detail", totalAyahs: 54 },
  { number: 42, name: "Ash-Shura", englishName: "The Consultation", totalAyahs: 53 },
  { number: 43, name: "Az-Zukhruf", englishName: "The Ornaments Of Gold", totalAyahs: 89 },
  { number: 44, name: "Ad-Dukhan", englishName: "The Smoke", totalAyahs: 59 },
  { number: 45, name: "Al-Jathiyah", englishName: "The Crouching", totalAyahs: 37 },
  { number: 46, name: "Al-Ahqaf", englishName: "The Wind-Curved Sandhills", totalAyahs: 35 },
  { number: 47, name: "Muhammad", englishName: "Muhammad", totalAyahs: 38 },
  { number: 48, name: "Al-Fath", englishName: "The Victory", totalAyahs: 29 },
  { number: 49, name: "Al-Hujurat", englishName: "The Rooms", totalAyahs: 18 },
  { number: 50, name: "Qaf", englishName: "Qaf", totalAyahs: 45 },
  { number: 51, name: "Adh-Dhariyat", englishName: "The Winnowing Winds", totalAyahs: 60 },
  { number: 52, name: "At-Tur", englishName: "The Mount", totalAyahs: 49 },
  { number: 53, name: "An-Najm", englishName: "The Star", totalAyahs: 62 },
  { number: 54, name: "Al-Qamar", englishName: "The Moon", totalAyahs: 55 },
  { number: 55, name: "Ar-Rahman", englishName: "The Beneficent", totalAyahs: 78 },
  { number: 56, name: "Al-Waqi'ah", englishName: "The Inevitable", totalAyahs: 96 },
  { number: 57, name: "Al-Hadid", englishName: "The Iron", totalAyahs: 29 },
  { number: 58, name: "Al-Mujadila", englishName: "The Pleading Woman", totalAyahs: 22 },
  { number: 59, name: "Al-Hashr", englishName: "The Exile", totalAyahs: 24 },
  { number: 60, name: "Al-Mumtahanah", englishName: "She That Is To Be Examined", totalAyahs: 13 },
  { number: 61, name: "As-Saf", englishName: "The Ranks", totalAyahs: 14 },
  { number: 62, name: "Al-Jumu'ah", englishName: "The Congregation, Friday", totalAyahs: 11 },
  { number: 63, name: "Al-Munafiqun", englishName: "The Hypocrites", totalAyahs: 11 },
  { number: 64, name: "At-Taghabun", englishName: "The Mutual Disillusion", totalAyahs: 18 },
  { number: 65, name: "At-Talaq", englishName: "The Divorce", totalAyahs: 12 },
  { number: 66, name: "At-Tahrim", englishName: "The Prohibition", totalAyahs: 12 },
  { number: 67, name: "Al-Mulk", englishName: "The Sovereignty", totalAyahs: 30 },
  { number: 68, name: "Al-Qalam", englishName: "The Pen", totalAyahs: 52 },
  { number: 69, name: "Al-Haqqah", englishName: "The Reality", totalAyahs: 52 },
  { number: 70, name: "Al-Ma'arij", englishName: "The Ascending Stairways", totalAyahs: 44 },
  { number: 71, name: "Nuh", englishName: "Noah", totalAyahs: 28 },
  { number: 72, name: "Al-Jinn", englishName: "The Jinn", totalAyahs: 28 },
  { number: 73, name: "Al-Muzzammil", englishName: "The Enshrouded One", totalAyahs: 20 },
  { number: 74, name: "Al-Muddaththir", englishName: "The Cloaked One", totalAyahs: 56 },
  { number: 75, name: "Al-Qiyamah", englishName: "The Resurrection", totalAyahs: 40 },
  { number: 76, name: "Al-Insan", englishName: "Man", totalAyahs: 31 },
  { number: 77, name: "Al-Mursalat", englishName: "The Emissaries", totalAyahs: 50 },
  { number: 78, name: "An-Naba", englishName: "The Tidings", totalAyahs: 40 },
  { number: 79, name: "An-Nazi'at", englishName: "Those Who Drag Forth", totalAyahs: 46 },
  { number: 80, name: "Abasa", englishName: "He Frowned", totalAyahs: 42 },
  { number: 81, name: "At-Takwir", englishName: "The Overthrowing", totalAyahs: 29 },
  { number: 82, name: "Al-Infitar", englishName: "The Cleaving", totalAyahs: 19 },
  { number: 83, name: "Al-Mutaffifin", englishName: "The Defrauding", totalAyahs: 36 },
  { number: 84, name: "Al-Inshiqaq", englishName: "The Sundering", totalAyahs: 25 },
  { number: 85, name: "Al-Buruj", englishName: "The Mansions Of The Stars", totalAyahs: 22 },
  { number: 86, name: "At-Tariq", englishName: "The Morning Star", totalAyahs: 17 },
  { number: 87, name: "Al-A'la", englishName: "The Most High", totalAyahs: 19 },
  { number: 88, name: "Al-Ghashiyah", englishName: "The Overwhelming", totalAyahs: 26 },
  { number: 89, name: "Al-Fajr", englishName: "The Dawn", totalAyahs: 30 },
  { number: 90, name: "Al-Balad", englishName: "The City", totalAyahs: 20 },
  { number: 91, name: "Ash-Shams", englishName: "The Sun", totalAyahs: 15 },
  { number: 92, name: "Al-Layl", englishName: "The Night", totalAyahs: 21 },
  { number: 93, name: "Ad-Duha", englishName: "The Morning Hours", totalAyahs: 11 },
  { number: 94, name: "Ash-Sharh", englishName: "The Relief", totalAyahs: 8 },
  { number: 95, name: "At-Tin", englishName: "The Fig", totalAyahs: 8 },
  { number: 96, name: "Al-Alaq", englishName: "The Clot", totalAyahs: 19 },
  { number: 97, name: "Al-Qadr", englishName: "The Power", totalAyahs: 5 },
  { number: 98, name: "Al-Bayyinah", englishName: "The Clear Proof", totalAyahs: 8 },
  { number: 99, name: "Az-Zalzalah", englishName: "The Earthquake", totalAyahs: 8 },
  { number: 100, name: "Al-Adiyat", englishName: "The Courser", totalAyahs: 11 },
  { number: 101, name: "Al-Qari'ah", englishName: "The Calamity", totalAyahs: 11 },
  { number: 102, name: "At-Takathur", englishName: "The Rivalry In World Increase", totalAyahs: 8 },
  { number: 103, name: "Al-Asr", englishName: "The Declining Day", totalAyahs: 3 },
  { number: 104, name: "Al-Humazah", englishName: "The Traducer", totalAyahs: 9 },
  { number: 105, name: "Al-Fil", englishName: "The Elephant", totalAyahs: 5 },
  { number: 106, name: "Quraysh", englishName: "Quraysh", totalAyahs: 4 },
  { number: 107, name: "Al-Ma'un", englishName: "The Small Kindnesses", totalAyahs: 7 },
  { number: 108, name: "Al-Kawthar", englishName: "The Abundance", totalAyahs: 3 },
  { number: 109, name: "Al-Kafirun", englishName: "The Disbelievers", totalAyahs: 6 },
  { number: 110, name: "An-Nasr", englishName: "The Divine Support", totalAyahs: 3 },
  { number: 111, name: "Al-Masad", englishName: "The Palm Fiber", totalAyahs: 5 },
  { number: 112, name: "Al-Ikhlas", englishName: "The Sincerity", totalAyahs: 4 },
  { number: 113, name: "Al-Falaq", englishName: "The Daybreak", totalAyahs: 5 },
  { number: 114, name: "An-Nas", englishName: "Mankind", totalAyahs: 6 },
];
