// Removes everything prisma/seed-demo.ts created, plus every IdentifierCounter
// row, leaving the database exactly as a fresh `npm run db:seed` run would.
// Run via `npm run db:wipe:demo`.
//
// Identifies demo-created rows via prisma/demo-seed-manifest.json — the
// exact set of ids the seed run recorded, not a DB-level tag. Chosen over a
// schema column (e.g. `createdBySeed Boolean`) because it needs no
// migration, and over "everything in the table" because that's exactly
// what makes the real-record guard below impossible to express: this file
// needs to tell "a demo row" apart from "a real one added since," and a
// blanket delete can't. The manifest is gitignored and regenerated by every
// seed run — see .gitignore's own comment.

const { prisma } = await import("../src/db/client.js");
const fs = await import("node:fs/promises");

interface DemoSeedManifest {
  createdAt: string;
  userIds: string[];
  staffIds: string[];
  staffNumbers: string[];
  parentIds: string[];
  studentIds: string[];
  admissionNumbers: string[];
  academicSessionIds: string[];
  termIds: string[];
  classIds: string[];
  subjectIds: string[];
  assessmentComponentIds: string[];
  gradingScaleIds: string[];
  traitIds: string[];
  timeSlotIds: string[];
  classSubjectAssignmentIds: string[];
  classFormTeacherIds: string[];
  timetableEntryIds: string[];
  feeStructureIds: string[];
  attendanceSessionIds: string[];
  admissionEnquiryIds: string[];
}

async function loadManifest(): Promise<DemoSeedManifest> {
  const manifestPath = new URL("./demo-seed-manifest.json", import.meta.url);
  try {
    const raw = await fs.readFile(manifestPath, "utf-8");
    return JSON.parse(raw) as DemoSeedManifest;
  } catch {
    console.error(
      [
        "",
        "No prisma/demo-seed-manifest.json found — nothing to wipe, or the manifest was lost.",
        "This script only removes what it can positively identify as demo-seed output; without",
        "the manifest there is nothing to safely delete, so it refuses rather than guessing.",
        "",
      ].join("\n"),
    );
    process.exit(1);
  }
}

/// Refuses if any Student/Staff row exists whose number the manifest never
/// recorded — once a real record exists, the counter (and the rest of the
/// demo dataset it's entangled with) can no longer be safely wiped: a real
/// student might be enrolled in a demo-seed class, linked to a demo-seed
/// parent's sibling, etc. Loud refusal beats a wipe that silently takes a
/// real record down with it.
async function guardAgainstRealRecords(manifest: DemoSeedManifest): Promise<void> {
  const [allStudents, allStaff] = await Promise.all([
    prisma.student.findMany({ select: { admissionNumber: true } }),
    prisma.staff.findMany({ select: { staffNumber: true } }),
  ]);
  const knownAdmissionNumbers = new Set(manifest.admissionNumbers);
  const knownStaffNumbers = new Set(manifest.staffNumbers);
  const unknownStudents = allStudents.filter((s) => !knownAdmissionNumbers.has(s.admissionNumber));
  const unknownStaff = allStaff.filter((s) => !knownStaffNumbers.has(s.staffNumber));

  if (unknownStudents.length > 0 || unknownStaff.length > 0) {
    console.error(
      [
        "",
        "Refusing to wipe: found record(s) the demo seed did not create.",
        unknownStudents.length > 0
          ? `Student admission number(s) not in the manifest: ${unknownStudents.map((s) => s.admissionNumber).join(", ")}`
          : undefined,
        unknownStaff.length > 0
          ? `Staff number(s) not in the manifest: ${unknownStaff.map((s) => s.staffNumber).join(", ")}`
          : undefined,
        "",
        "Once a real record exists, IdentifierCounter can no longer be safely reset — deleting it",
        "would let the next generated number collide with (or predate) a real one already issued.",
        "This script will not delete anything.",
        "",
      ]
        .filter((line): line is string => line !== undefined)
        .join("\n"),
    );
    process.exit(1);
  }
}

async function wipe(manifest: DemoSeedManifest): Promise<void> {
  const userIds = manifest.userIds;
  const studentIds = manifest.studentIds;

  // Same child-before-parent order as src/test/resetDb.ts, scoped to this
  // manifest's ids instead of unconditional truncation — see that file's
  // own comment for why the order matters (several FKs are deliberately
  // not cascade-delete).
  await prisma.$transaction([
    prisma.auditLog.deleteMany({ where: { actorUserId: { in: userIds } } }),
    // The one unconditional delete: every row, regardless of prefix — the
    // whole point of this script existing is making the counter safe to
    // reset, which only means something if it's actually reset to empty.
    prisma.identifierCounter.deleteMany(),
    prisma.notificationEvent.deleteMany({ where: { recipientUserId: { in: userIds } } }),
    prisma.resultOverride.deleteMany({ where: { result: { studentId: { in: studentIds } } } }),
    prisma.sessionSubjectAverage.deleteMany({ where: { sessionResult: { studentId: { in: studentIds } } } }),
    prisma.sessionResult.deleteMany({ where: { studentId: { in: studentIds } } }),
    prisma.result.deleteMany({ where: { studentId: { in: studentIds } } }),
    prisma.rating.deleteMany({ where: { studentId: { in: studentIds } } }),
    prisma.trait.deleteMany({ where: { id: { in: manifest.traitIds } } }),
    prisma.subjectResult.deleteMany({ where: { studentId: { in: studentIds } } }),
    prisma.score.deleteMany({ where: { studentId: { in: studentIds } } }),
    prisma.timetableEntry.deleteMany({ where: { id: { in: manifest.timetableEntryIds } } }),
    prisma.classSubjectAssignment.deleteMany({ where: { id: { in: manifest.classSubjectAssignmentIds } } }),
    prisma.classFormTeacher.deleteMany({ where: { id: { in: manifest.classFormTeacherIds } } }),
    prisma.attendanceRecord.deleteMany({ where: { attendanceSessionId: { in: manifest.attendanceSessionIds } } }),
    prisma.attendanceSession.deleteMany({ where: { id: { in: manifest.attendanceSessionIds } } }),
    prisma.studentQrCode.deleteMany({ where: { studentId: { in: studentIds } } }),
    prisma.receipt.deleteMany({ where: { payment: { feeObligation: { studentId: { in: studentIds } } } } }),
    prisma.payment.deleteMany({ where: { feeObligation: { studentId: { in: studentIds } } } }),
    prisma.feeObligation.deleteMany({ where: { studentId: { in: studentIds } } }),
    prisma.feeStructure.deleteMany({ where: { id: { in: manifest.feeStructureIds } } }),
    prisma.madrassahProgress.deleteMany({ where: { studentId: { in: studentIds } } }),
    prisma.admissionEnquiry.deleteMany({ where: { id: { in: manifest.admissionEnquiryIds } } }),
    prisma.enrollment.deleteMany({ where: { studentId: { in: studentIds } } }),
    prisma.studentParent.deleteMany({ where: { studentId: { in: studentIds } } }),
    prisma.refreshToken.deleteMany({ where: { userId: { in: userIds } } }),
    prisma.passwordResetToken.deleteMany({ where: { userId: { in: userIds } } }),
    prisma.staff.deleteMany({ where: { id: { in: manifest.staffIds } } }),
    prisma.parent.deleteMany({ where: { id: { in: manifest.parentIds } } }),
    prisma.student.deleteMany({ where: { id: { in: studentIds } } }),
    prisma.gradeBand.deleteMany({ where: { gradingScaleId: { in: manifest.gradingScaleIds } } }),
    prisma.gradingScale.deleteMany({ where: { id: { in: manifest.gradingScaleIds } } }),
    prisma.assessmentComponent.deleteMany({ where: { id: { in: manifest.assessmentComponentIds } } }),
    prisma.timeSlot.deleteMany({ where: { id: { in: manifest.timeSlotIds } } }),
    prisma.term.deleteMany({ where: { id: { in: manifest.termIds } } }),
    prisma.subject.deleteMany({ where: { id: { in: manifest.subjectIds } } }),
    prisma.class.deleteMany({ where: { id: { in: manifest.classIds } } }),
    // No School row here — seed-demo.ts never creates or touches one.
    prisma.academicSession.deleteMany({ where: { id: { in: manifest.academicSessionIds } } }),
    prisma.userRole.deleteMany({ where: { userId: { in: userIds } } }),
    prisma.user.deleteMany({ where: { id: { in: userIds } } }),
  ]);
}

async function main() {
  const manifest = await loadManifest();
  await guardAgainstRealRecords(manifest);
  await wipe(manifest);

  const manifestPath = new URL("./demo-seed-manifest.json", import.meta.url);
  await fs.unlink(manifestPath);

  const remainingUsers = await prisma.user.count();
  const remainingCounters = await prisma.identifierCounter.count();
  console.log(
    [
      "",
      "Demo data wiped.",
      `Users remaining (bootstrap admin + anything else prisma/seed.ts creates): ${remainingUsers}`,
      `IdentifierCounter rows remaining: ${remainingCounters} (should be 0 — the next admission/staff number`,
      "starts fresh at FIA/2026/001 / FIA/ST2026/001).",
      "",
    ].join("\n"),
  );
}

main()
  .catch((err: unknown) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => {
    void prisma.$disconnect();
  });
